### ISSUE TITLE
Illegal characters in path stopping output being produced

### ISSUE THREAD

**Issue by andydavidsmith** [nareshnavinash/newman-run#18]
using 1.2.4 newman-run and running command
newman-run -f feed.json where feed.json is like
```
{
	"runs": [
		{
			"collection": "./collections/Call.postman_collection.json",
			"environment": "./environment/qa.postman_environment.json"
		}
	]
}
```
I get the following error
```
C:\npm\prefix\node_modules\newman-run\node_modules\mkdirp\lib\path-arg.js:20
     throw Object.assign(new Error('Illegal characters in path.'), {
      ^

Error: Illegal characters in path.
    at pathArg (C:\npm\prefix\node_modules\newman-run\node_modules\mkdirp\lib\path-arg.js:20:27)
    at mkdirp (C:\npm\prefix\node_modules\newman-run\node_modules\mkdirp\index.js:10:10)
    at C:\npm\prefix\node_modules\newman-run\node_modules\newman\lib\run\export-file.js:97:17
    at nextTask (C:\npm\prefix\node_modules\newman-run\node_modules\async\dist\async.js:5787:13)
    at Object.waterfall (C:\npm\prefix\node_modules\newman-run\node_modules\async\dist\async.js:5798:9)
    at Object.awaitable [as waterfall] (C:\npm\prefix\node_modules\newman-run\node_modules\async\dist\async.js:211:32)
    at module.exports (C:\npm\prefix\node_modules\newman-run\node_modules\newman\lib\run\export-file.js:95:15)
    at C:\npm\prefix\node_modules\newman-run\node_modules\async\internal\withoutIndex.js:8:40
    at eachOfArrayLike (C:\npm\prefix\node_modules\newman-run\node_modules\async\eachOf.js:61:9)
    at eachOf (C:\npm\prefix\node_modules\newman-run\node_modules\async\eachOf.js:181:12)
    at awaitable (C:\npm\prefix\node_modules\newman-run\node_modules\async\internal\awaitify.js:13:28)
    at eachLimit (C:\npm\prefix\node_modules\newman-run\node_modules\async\each.js:125:31)
    at awaitable (C:\npm\prefix\node_modules\newman-run\node_modules\async\internal\awaitify.js:13:28)
    at done (C:\npm\prefix\node_modules\newman-run\node_modules\newman\lib\run\index.js:343:21)
    at C:\npm\prefix\node_modules\newman-run\node_modules\postman-runtime\lib\backpack\index.js:58:34
    at PostmanCollectionRun._process (C:\npm\prefix\node_modules\newman-run\node_modules\postman-runtime\lib\runner\run.js:160:13) {
  path: 'D:\\a\\1\\s\\reports\\json\\D:\\a\\1\\s\\collections',
  code: 'EINVAL'
```

**Comment by MichaelLiss** [comment]
I am getting the same error

**Comment by nareshnavinash** [comment]
Hello,

newman-run is supported only in mac and linux environments, please try to use the package directly in a CI environment by mentioning the file path in linux format.
