### ISSUE TITLE
npm run serve-allure return missing script: serve-allure

### ISSUE THREAD

**Issue by petrisorionel** [nareshnavinash/newman-run#4]
```
npm run serve-allure
npm ERR! missing script: serve-allure

npm ERR! A complete log of this run can be found in:
npm ERR!     \npm-cache\_logs\2021-01-15T21_38_46_285Z-debug.log


0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\NVM\\v12.18.3\\node.exe',
1 verbose cli   'C:\\NVM\\v12.18.3\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'serve-allure'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose stack Error: missing script: serve-allure
4 verbose stack     at run (C:\NVM\v12.18.3\node_modules\npm\lib\run-script.js:155:19)
4 verbose stack     at C:\NVM\v12.18.3\node_modules\npm\lib\run-script.js:63:5
4 verbose stack     at C:\NVM\v12.18.3\node_modules\npm\node_modules\read-package-json\read-json.js:116:5
4 verbose stack     at C:\NVM\v12.18.3\node_modules\npm\node_modules\read-package-json\read-json.js:436:5
4 verbose stack     at checkBinReferences_ (C:\NVM\v12.18.3\node_modules\npm\node_modules\read-package-json\read-json.js:391:45)
4 verbose stack     at final (C:\NVM\v12.18.3\node_modules\npm\node_modules\read-package-json\read-json.js:434:3)
4 verbose stack     at then (C:\NVM\v12.18.3\node_modules\npm\node_modules\read-package-json\read-json.js:161:5)
4 verbose stack     at C:\NVM\v12.18.3\node_modules\npm\node_modules\read-package-json\read-json.js:382:12
4 verbose stack     at C:\NVM\v12.18.3\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:123:16
4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
5 verbose cwd 
6 verbose Windows_NT 10.0.19041
7 verbose argv "C:\\NVM\\v12.18.3\\node.exe" "C:\\NVM\\v12.18.3\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve-allure"
8 verbose node v12.18.3
9 verbose npm  v6.14.6
10 error missing script: serve-allure
11 verbose exit [ 1, true ]


```

**Comment by nareshnavinash** [comment]
@petrisorionel this is because of the typo in the readme file, I have updated the readme now. You can generate the allure reports by `allure serve reports/allure`. To install the allure command line you can follow https://docs.qameta.io/allure/ and install it in your respective machines. Please feel free to open the issue if not resolved by this.
